### ISSUE TITLE
lf_input = input[:, self.ch_in_hf * 4:, ...]

### ISSUE THREAD

**Issue by CharmsYANG** [iacolippo/octconv-pytorch#2]
why when we get the lf_input, we get the lf_input=input[:, self.ch_in_hf * 4:, ...] (same with the hf_input). for example, when input shape is[2,10,n,n]; the alphas=(0.5, 0.5); it's said that self.ch_in_hf = 5, so the input[:, self.ch_in_hf * 4:, ...] will out of range.so is there any mistake?

**Comment by Periter** [comment]
> hf_output = hf_output.reshape(-1, 4 * self.ch_out_hf, fmap_size, fmap_size) in the line 61.
In fact, the output after first conv, the featurmap's size is (2,6,16,16), then forward it into conv2.
Through channel increase exchange for size decrease.

**Comment by CharmsYANG** [comment]
@Periter thx for the explanation, i get the piont.

**Comment by weycui** [comment]
Hello,sir. I got the  RuntimeError: sizes must be non-negative, when I run your model on pytorch 0.4.1  why？the pytorch version? or other

**Comment by transcendentsky** [comment]
Pytorch 1.0.1 seems ok

**Comment by CharmsYANG** [comment]
@weycui have you change the parameters?

**Comment by weycui** [comment]
@CharmsYANG  No,I havn't

**Comment by weycui** [comment]
I updated my pytorch version to 1.0.1 just now. It  can run   Thx@transcendentsky @CharmsYANG

**Comment by iacolippo** [comment]
Hey all, good that you solved the issue without needing me :-)

Just for clarification if someone stumbles upon this issue in the future:
- this module is written for Pytorch 1.0
- the module outputs a unique volume that combines low freq and high freq. High freq maps are 4 times as big, so it reshapes them to be the same as the low freq output and then stacks everything across depth.
- according to the paper, the first convolutional layer should have `alpha_in = 0` and the last one `alpha_out=0`

**Comment by CharmsYANG** [comment]
@iacolippo its really clear now, thx very much.
